apiVersion: skaffold/v3
kind: Config
metadata:
  name: app
build:
  artifacts:
    - image: link-service
      context: .
      docker:
        dockerfile: link-service/Dockerfile
    - image: auth-server
      context: .
      docker:
        dockerfile: authentication-service/Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true
manifests:
  rawYaml:
    - kubernetes-manifests/*.yaml
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: link-service
    port: 8080
    localPort: 8080
  - resourceType: service
    resourceName: auth-server
    port: 8080
    localPort: 8081