apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-server
spec:
  selector:
    matchLabels:
      app: link-server
  template:
    metadata:
      labels:
        app: link-server
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; usleep 250000; done;']
      - name: wait-for-migration
        image: bitnami/kubectl
        command:
        - 'sh'
        - '-c'
        - 'kubectl wait --for=condition=complete job/db-migrate --timeout=5m'
      containers:
      - name: link-server
        image: link-server
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: url
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 1
          failureThreshold: 30
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: link-server
spec:
  type: ClusterIP
  selector:
    app: link-server
  ports:
  - port: 8080
    targetPort: 8080