apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkservice
spec:
  selector:
    matchLabels:
      app: linkservice
  template:
    metadata:
      labels:
        app: linkservice
    spec:
      initContainers:
      - name: wait-for-migration
        image: bitnami/kubectl
        command:
        - 'sh'
        - '-c'
        - 'kubectl wait --for=condition=complete job/db-migrate --timeout=5m'
      containers:
      - name: server
        image: linkservice
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: url
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: linkservice
spec:
  type: ClusterIP
  selector:
    app: linkservice
  ports:
  - port: 8080
    targetPort: 8080