apiVersion: v1
kind: Secret
metadata:
  name: link-db-secrets
type: Opaque
stringData:
  url: postgres://urluser:urlpass@link-db:5432/link-db?sslmode=disable
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: link-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: link-db
  template:
    metadata:
      labels:
        app: link-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: link-db
        - name: POSTGRES_USER
          value: urluser
        - name: POSTGRES_PASSWORD
          value: urlpass
        volumeMounts:
        - name: link-db-storage
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "urluser"]
          periodSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: link-db-storage
        persistentVolumeClaim:
          claimName: link-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: link-db
spec:
  selector:
    app: link-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-service
spec:
  selector:
    matchLabels:
      app: link-service
  template:
    metadata:
      labels:
        app: link-service
    spec:
      initContainers:
      - name: wait-for-link-db
        image: busybox
        command: ['sh', '-c', 'until nc -z link-db 5432; do echo waiting for link-db; usleep 250000; done;']
      - name: run-migrations
        image: link-service
        command: ['/app/migrate', '-path', '/app/migrations', '-database', '$(DATABASE_URL)', 'up']
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: link-db-secrets
              key: url
      containers:
      - name: link-service
        image: link-service
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: link-db-secrets
              key: url
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 10
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 5
          failureThreshold: 12
---
apiVersion: v1
kind: Service
metadata:
  name: link-service
spec:
  type: ClusterIP
  selector:
    app: link-service
  ports:
  - port: 8080
    targetPort: 8080