apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkservice
spec:
  selector:
    matchLabels:
      app: linkservice
  template:
    metadata:
      labels:
        app: linkservice
    spec:
      initContainers:
      - name: db-migrate
        image: linkservice
        command: ["migrate"]
        args: ["-path", "/app/migrations", "-database", "$(DATABASE_URL)", "up"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: url
      containers:
      - name: server
        image: linkservice
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: url
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: linkservice
spec:
  type: ClusterIP
  selector:
    app: linkservice
  ports:
  - port: 8080
    targetPort: 8080