apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkservice
spec:
  selector:
    matchLabels:
      app: linkservice
  template:
    metadata:
      labels:
        app: linkservice
    spec:
      containers:
      - name: server
        image: linkservice
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: linkservice
spec:
  type: ClusterIP
  selector:
    app: linkservice
  ports:
  - port: 8080
    targetPort: 8080